import { NavBar } from "@/components/NavBar";
import { TaskProvider } from "../context/TaskContext";
import "./globals.css";
import { Toaster } from "./Toaster";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TaskProvider>
          <NavBar />
          {children}
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}
